AWS_ACCESS_KEY: "AKIAQK36ABPF4K3QL2JD"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "avneesh-sawhney-flixter"
AWS_REGION: "us-east-1"
SECRET_KEY: 'sk_test_Svut9fL1bzyRxIDtVsEOKrjw00pUJ7jvpo'
PUBLISHABLE_KEY: 'pk_test_WbsfFV7tU0MQIkNCIVS3zmh200ocGL6PMd'